### ISSUE TITLE
Tests for Shortrange Potential

### ISSUE THREAD

**Issue by maqnius** [maqnius/compscie-mc#26]
Endergebnisse numerisch testen mit vorberechneter Lösung. @Stefaanhess - u know what I mean

**Comment by SimonTreu** [comment]
erledigt?

**Comment by Stefaanhess** [comment]
Mach ich morgen fertig
SimonTreu <notifications@github.com> schrieb am Fr. 10. Feb. 2017 um 23:51:

**Comment by SimonTreu** [comment]
Aso nene wollte nicht stressen!
