### ISSUE TITLE
Periodicity

### ISSUE THREAD

**Issue by SimonTreu** [maqnius/compscie-mc#9]
In neighboring lists we need to take care of the periodic boundary conditions! For example if the cutoff is much larger then the box size we would get each particle several times.

**Comment by thadler** [comment]
I'm busy the following days but I'll take care of it on Sunday!

 

 

 

-----Ursprüngliche Mitteilung----- 
Von: SimonTreu <notifications@github.com>
An: maqnius/compscie-mc <compscie-mc@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Verschickt: Mi, 25. Jan 2017 16:50
Betreff: [maqnius/compscie-mc] Periodicity (#9)



In neighboring lists we need to take care of the periodic boundary conditions! For example if the cutoff is much larger then the box size we would get each particle several times.

**Comment by jaappedersen** [comment]
cutoff will be smaller then half of the box length, so taking particles several times will not happen
